### PR TITLE
Remove abandoned OCaml r2pipe, update maintained one

### PR DESCRIPTION
**Pull request by XVilka**
Addressing https://github.com/radare/radare2-r2pipe/issues/39

### CODE REVIEW

**Comment by XVilka** [comment]
@radare this is what I was talking about - cleanup the old, update the new one.

**Comment by radare** [comment]
The “old” is the official one published in opam...

**Comment by XVilka** [comment]
@radare they both are published in opam, both are "official". But I asked an author of the old one to deprecate it in the opam repository and now it is deprecated and recommends to use the new one.

**Comment by XVilka** [comment]
See for yourself https://github.com/ocaml/opam-repository/commit/ab452ede247e8cd449a7906385ecd1514de00194

**Comment by XVilka** [comment]
So?

**Comment by radare** [comment]
What do u want to remove if our code is newer than the one in opam?

**Comment by XVilka** [comment]
Please reread my message again. I updated the code here and in opam.

**Comment by XVilka** [comment]
@radare it is done already. There are two implementations here: ocaml-r2 and ocaml directories.
The one is old and unmaintained (from the https://github.com/binoopang/r2pipe-ocaml repo), the second is more featureful, updated and maintained (last commit 3 days ago, main repo https://github.com/fxfactorial/ocaml-radare2 ). I asked the author of r2pipe-ocaml (the first one) to deprecate his implementation, he did it. So now recommended is the only one. Since in this repository we have two copies - I just think we need to remove the old implementation, keeping (and updating) the new one.

**Pull request merged**
