### PR TITLE
fixes #88: small update open_sync.py (remove utf-8 decodes)

### LINKED ISSUE #88: utf8-decode! Very easy fix.
Hi guys! Please remove this decode as sometimes the output isn't utf8-decodeable. I'm referring to the file open_sync.py where I think you should remove the ".decode('utf-8')" piece of code in the _cmd_process function. thanks!

### PR DESCRIPTION
**Pull request by meiraxx**
Hi! Please remove these decodes as sometimes the output isn't utf8-decodeable. 
https://user-images.githubusercontent.com/25626434/50499947-95937180-0a45-11e9-9607-2087a7aa73ad.png

### CODE REVIEW

**Comment by a1ext** [comment]
I think there have to be safe unicode decoding, to make the output the string on both **Python 2** and **Python 3** (instead of bytes on Python 3). You can try to decode, and if it successfully decoded - return unicode, instead - return as is

**Comment by radare** [comment]
wat du

**Comment by meiraxx** [comment]
Do what the panda said, I only tested it on python 2, but since you want compatibility between both (as you should), I think that's the best option

**Comment by a1ext** [comment]
I will handle this PR later (next week)

**Pull request merged**
