### PR TITLE
Added support for opening project files.

### PR DESCRIPTION
**Pull request by katshup**
This is a proposal for fixing issue #14

### CODE REVIEW

**Comment by radare** [comment]
What about using the options parameter to hold the project like ['-P', projectName] instead of adding one parameter more that will break many scripts using the current api?

**Comment by katshup** [comment]
So I guess where the flags are being inserted could be changed. 
```python
self._cmd = self._cmd_process
cmd = ["radare2", "-q0", filename]
cmd = cmd[:2] + flags + cmd[2:]
```

Users who would want to open a project would only need to supply the '-p' flag, but it would also need to be last one in the list. For whatever reason leaving filename as an empty string would cause Radare to launch with the expectation of having a binary file passed in, I suppose given from the number of arguments being passed through via Popen.

**Comment by radare** [comment]
If options is a string instead of an array load the project? This seems correct for you?

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
this will break the api, so better handle ['-pprjname']

**Pull request closed without merging**
